# This is a basic workflow to help you get started with Actions

name: Build (auto)

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_run:
    workflows: [Lint]
    branches: [develop, main]
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   
      # Set docker image names.
      - name: Setup env variables
        run: |
          echo "DOCKER_SERVICE=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.event.workflow_run.head_branch }}

# Login against a Docker registry except on PR
# https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

# if below step is skipped this build is a tag build. Can be used for skipping other steps.
      - name: Is Tag Build
        id: tag
        if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}  

# Build
      - name: Build
        run: ./scripts/build.sh ${{ env.DOCKER_SERVICE }} ${{ github.event.repository.url }}

# Push to Github
      - name: Tag service git id docker image
        if: ${{ steps.tag.conclusion == 'skipped' }}
        run: ./scripts/docker-tag.sh ${{ env.DOCKER_SERVICE }}:latest ${{ env.DOCKER_SERVICE }}:${{ github.event.workflow_run.head_sha }}

      - name: Tag service git id docker image
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./scripts/docker-tag.sh ${{ env.DOCKER_SERVICE }}:latest ${{ env.DOCKER_SERVICE }}:${{ github.sha }}

      - name: Tag service dev docker image
        run: ./scripts/docker-tag.sh ${{ env.DOCKER_SERVICE }}:latest ${{ env.DOCKER_SERVICE }}:dev

      - name: Push service git id docker image.
        if: ${{ steps.tag.conclusion == 'skipped' }}
        run: ./scripts/docker-push.sh ${{ env.DOCKER_SERVICE }}:${{ github.event.workflow_run.head_sha }}

      - name: Push service git id docker image.
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./scripts/docker-push.sh ${{ env.DOCKER_SERVICE }}:${{ github.sha }}

      - name: Push dev docker image.
        run: ./scripts/docker-push.sh ${{ env.DOCKER_SERVICE }}:dev

      - name: Push latest service docker image
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./scripts/docker-push.sh ${{ env.DOCKER_SERVICE }}:latest

      - name: Tag version service docker image
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./scripts/docker-tag.sh ${{ env.DOCKER_SERVICE }}:latest ${{ env.DOCKER_SERVICE }}:${{ steps.tag.outputs.VERSION }}

      - name: Push version service docker image.
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./scripts/docker-push.sh ${{ env.DOCKER_SERVICE }}:${{ steps.tag.outputs.VERSION }}